/* Coordinated force, motion and spectral views. All values come from the same samples as the main animation. */
const LabExtension=(()=>{
 const $=s=>document.querySelector(s),B='#1664b7',O='#b84f19',V='#7951a8',T='#0b746c',I='#172d40';
 const num=(v,n=2)=>Number(v).toFixed(n),signed=v=>(v>=0?'+':'')+num(v);
 let host,idx=-1,p={},sample,end=8,scale=10,views={3:'phase',5:'time'},lastState=null,maxTrace=0,plotSerial=0,record=[];
 function ensure(){if(!host){host=document.createElement('div');host.id='deep-lab';$('.chart-wrap').insertAdjacentElement('beforebegin',host);document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){views[idx]=b.dataset.view;applyView();if(lastState)draw(lastState);}const option=e.target.closest('[data-diag-setting]');if(option){const prior=lastState;PhaseViews.set(option.dataset.diagSetting,option.dataset.value);setup(idx,p,sample,end,scale);if(prior)draw(prior);}});document.addEventListener('change',e=>{if(e.target.id==='view-select'){views[idx]=e.target.value;applyView();if(lastState)draw(lastState);}});}return host;}
 function linePlot(rows){
  let svg='';const h=126,points=record.length,x=t=>92+t/end*516,serial=plotSerial++;
  rows.forEach((row,j)=>{const top=j*h,y0=top+75,lim=row.limit||scale;
    svg+=`<text x="12" y="${top+25}" font-size="23" fill="${I}">${row.label}</text><text x="610" y="${top+25}" font-size="21" text-anchor="end" fill="#536575">±${num(lim,lim<1?2:1)} ${row.unit}</text><line x1="92" x2="608" y1="${y0}" y2="${y0}" stroke="#c9d5e1"/>`;
    for(let k=0;k<=4;k++)svg+=`<line x1="${92+k*129}" x2="${92+k*129}" y1="${top+35}" y2="${top+113}" stroke="#e8edf3"/>`;
    svg+=`<defs><clipPath id="deep-clip-${serial}-${j}"><rect x="92" y="${top+34}" width="516" height="80"/></clipPath></defs>`;
    row.curves.forEach(c=>{let d='';for(let n=0;n<points;n++){const t=n*end/(points-1),v=c.value(record[n]);d+=`${n?'L':'M'}${x(t)},${y0-v/lim*36} `;}svg+=`<path d="${d}" fill="none" stroke="${c.color}" stroke-width="3" clip-path="url(#deep-clip-${serial}-${j})" ${c.dash?'stroke-dasharray="7 6"':''}/>`;});
    svg+=`<line class="deep-cursor" x1="92" x2="92" y1="${top+34}" y2="${top+113}" stroke="${T}" stroke-width="2"/>`;
  });
  for(let k=0;k<=4;k++)svg+=`<text x="${92+k*129}" y="${rows.length*h+15}" text-anchor="middle" font-size="21" fill="#536575">${num(k*end/4,1)}</text>`;
  return `<svg viewBox="0 0 640 ${rows.length*h+28}" class="deep-chart" role="img" aria-label="共用时间轴的同步时程">${svg}</svg>`;
 }
 function setup(i,params,fn,duration,max){ensure();idx=i;p=params;sample=fn;end=duration;scale=max;lastState=null;PhaseViews.reset();
  $('#view-navigation').innerHTML='';
  if(i>5){host.hidden=true;$('.chart-wrap').hidden=false;return;}
  host.hidden=false;
  if(i<3||i===4){host.innerHTML=i===4?PhaseViews.pulse(p,sample,end):PhaseViews.free(i,p,sample,end,scale);$('.chart-wrap').hidden=true;$('#view-navigation').innerHTML='<p class="view-purpose">同步查看：位移时程与包络 · 位移—速度轨迹</p>';return;}
  const count=Math.max(801,Math.ceil(end*Math.max(p.frequency||0,sample(0).fn||1)*64)+1);record=Array.from({length:count},(_,n)=>sample(n*end/(count-1)));maxTrace=Math.max(...record.map(r=>i===3?Math.max(Math.abs(r.x),Math.abs(r.ma),Math.abs(r.cv),Math.abs(r.kx),Math.abs(r.F)):Math.abs(r.x)));
  const tabs=i===3?[['phase','相位与两种轨迹'],['frequency','D 与相位频响'],['envelope','启动分解与包络'],['forces','力的平衡'],['motion','位移·速度·加速度']]:[['time','输入与响应时程'],['spectrum','谱的转换']];
  $('#view-navigation').innerHTML=`<label class="view-select-label" for="view-select">观察内容</label><select id="view-select">${tabs.map(([v,label])=>`<option value="${v}" ${views[i]===v?'selected':''}>${label}</option>`).join('')}</select><div class="deep-tabs" role="tablist" aria-label="观察角度">${tabs.map(([v,label])=>`<button role="tab" data-view="${v}" aria-selected="${views[i]===v}">${label}</button>`).join('')}</div>`;
  host.innerHTML='<div class="deep-context"></div><div class="deep-panel"></div>';
  if(i===3){renderForces();const extra=PhaseViews.resonance(p,sample,end,scale);host.querySelector('[data-panel="phase"]').innerHTML=extra.phase;host.querySelector('.deep-panel').insertAdjacentHTML('beforeend',`<div data-panel="frequency">${extra.frequency}</div><div data-panel="envelope">${extra.envelope}</div>`);host.querySelector('.deep-panel').append(host.querySelector('#range-warning'),host.querySelector('[data-param="displayRange"]'));}else renderSpectrum();applyView();
 }
 function renderForces(){
  const r=sample(0),probe=record,peak=key=>Math.max(.01,...probe.map(v=>Math.abs(v[key])))*1.1;
  const forceRows=[{label:'紫：惯性项 ma　蓝：弹性项 kx',unit:'N',curves:[{color:V,value:r=>r.ma},{color:B,value:r=>r.kx}]},{label:'绿：阻尼项 cẋ　橙虚线：外力 F',unit:'N',curves:[{color:T,value:r=>r.cv},{color:O,value:r=>r.F,dash:true}]}];
  const wn=Math.sqrt(p.stiffness/p.mass);
  const motionRows=[{label:'位移 x/x静',unit:'无量纲',limit:scale,curves:[{color:B,value:r=>r.xSI*p.stiffness}]},{label:'速度 v/(ωₙx静)',unit:'无量纲',limit:scale,curves:[{color:T,value:r=>r.vSI*p.stiffness/wn}]},{label:'加速度 a/(ωₙ²x静)',unit:'无量纲',limit:scale,curves:[{color:V,value:r=>r.aSI*p.mass}]}];
  $('.deep-context').innerHTML=`<div class="system-identity"><span>结构固有频率 fₙ <b>${num(r.fn)} Hz</b></span><span>频率比 f/fₙ <b>${num(r.ratio)} 倍</b></span><button id="tune-frequency" class="text-button">对准结构固有频率</button></div><p class="quiet state-contract">${p.response==='steady'?'当前为稳态：已经持续推动了一段时间。':'当前从静止启动：开始时位移和速度均为零。'}实际阻尼系数 c = ${num(r.c)} N·s/m。</p>`;
  $('.deep-panel').innerHTML=`<div data-panel="forces"><div class="live-equation" aria-label="实时动力平衡"><div class="equation-title">mẍ + cẋ + kx = F(t)</div><div class="equation-values"><span style="color:${V}">惯性项 ma<b id="force-ma"></b></span><span style="color:${T}">阻尼项 cẋ<b id="force-cv"></b></span><span style="color:${B}">弹性项 kx<b id="force-kx"></b></span><span style="color:${O}">外力 F<b id="force-f"></b></span></div><p id="force-sum" class="force-sum"></p><details><summary>查看数值平衡</summary><p id="force-check" class="quiet"></p></details></div><p class="micro-question">暂停或拖动共同时间游标，同时比较惯性项与弹性项之和，以及阻尼项与外力。</p>${linePlot(forceRows)}<p class="quiet">两行共用时间轴与力刻度；力项图显示完整记录，竖线是当前时刻。这里画方程左侧项，实际弹簧力和阻尼力分别是 −kx、−cẋ。</p></div><div data-panel="motion"><p class="quiet">各行都用手动固定量程；静力位移 x静=F₀/k，固有角频率 ωₙ=√(k/m)。</p>${linePlot(motionRows)}<div id="motion-values" class="readouts"></div><p class="quiet">三行共用时间轴与固定无量纲刻度；下方数值另列实际位移、速度和加速度。调频率或阻尼不会重设坐标。</p></div><div data-panel="phase"><div class="phase-stats"><span>外力频率<b>${num(p.frequency)} Hz</b></span><span>稳态响应频率<b>${num(p.frequency)} Hz</b></span><span>位移滞后<b>${num(r.phase*180/Math.PI,1)}°</b></span></div><p class="micro-question">先数波峰，再比较峰高和出现时刻。相同频率，也能有不同响应。</p><p class="quiet">${p.response==='start'?'启动阶段含固有振动成分，当前总响应未必是单频；上面列的是最终稳态特性。':'相位滞后对应 '+num(r.phase/(2*Math.PI*p.frequency),3)+' s；调整频率后，相位与幅值都会改变。'}</p></div><p id="range-warning" class="warning" hidden></p><button data-param="displayRange" data-value="${scale<50?50:scale<600?600:10}" class="text-button">${scale<50?'手动展宽至 ±50':scale<600?'手动展宽至 ±600':'恢复固定量程 ±10'}</button>`;
 }
 function renderSpectrum(){
  const r=sample(0),k=Physics.tau**2,weights=r.parts;
  const spectrum=(key,max,unit,color)=>{let s=`<line x1="58" x2="618" y1="142" y2="142" stroke="#c0cddb"/><text x="12" y="38" font-size="21" fill="#536575">${max}</text><text x="24" y="148" font-size="21" fill="#536575">0</text>`;if(key==='H'){let curve='';for(let n=0;n<=800;n++){const freq=n/800*2.2,ratio=freq/p.natural,H=1/(k*Math.hypot(1-ratio*ratio,2*p.damping*ratio));curve+=`${n?'L':'M'}${58+freq/2.2*560},${142-H/max*105} `;}s+=`<path d="${curve}" fill="none" stroke="${T}" stroke-width="2" opacity=".65"/>`;}weights.forEach((part,j)=>{const x=58+part.f/2.2*560,value=key==='input'?part.amp:key==='H'?part.D/k:part.amp*part.D/k*100,h=value/max*105;s+=`<line x1="${x}" x2="${x}" y1="142" y2="${142-h}" stroke="${color}" stroke-width="7"/><circle cx="${x}" cy="${142-h}" r="5" fill="${color}"/><text x="${x}" y="${132-h}" text-anchor="middle" font-size="22" fill="${I}">${num(value,key==='H'?3:2)}</text><text x="${x}" y="178" text-anchor="middle" font-size="22" fill="#536575">${part.f} Hz</text>`;});return `<svg class="spectrum-chart" viewBox="0 0 640 190" role="img" aria-label="${unit}离散谱">${s}</svg>`;};
  $('.deep-context').innerHTML=`<p class="quiet">每一列对应同一个频率。输入相位均为 0°；改变结构参数后，频率仍在原处。</p>`;
  $('.deep-panel').innerHTML=`<div data-panel="spectrum"><div class="spectrum-step"><h3><b>1</b> 荷载幅值谱 <small>N</small></h3>${spectrum('input',2,'荷载幅值 N',O)}</div><div class="spectrum-step"><h3><b>2</b> 逐频率转换 <small>柔度 |H| · m/N</small></h3>${spectrum('H',.65,'柔度 m/N',T)}<div class="spectral-phase">${weights.map(pt=>`<span>${pt.f} Hz<em>滞后 ${num(pt.phase*180/Math.PI,1)}°</em></span>`).join('')}</div></div><div class="spectrum-step"><h3><b>3</b> 响应位移幅值谱 <small>cm</small></h3>${spectrum('output',130,'响应位移幅值 cm',B)}</div><div class="spectral-equations">${weights.map(pt=>`<p><b>${pt.f} Hz</b>：${num(pt.amp)} N × ${num(pt.D/k,4)} m/N = <strong>${num(pt.amp*pt.D/k*100)} cm</strong>${pt.amp===0?'（未输入这一频率）':''}</p>`).join('')}</div><p class="quiet">绿色曲线是连续频率响应，三个圆点是输入频率处的柔度。三张图单位不同，分别使用固定刻度；不能直接比较柱高。它们是已知正弦分量的幅值谱，不是随机荷载的功率谱密度。</p><details><summary>如果手里的是功率谱呢？</summary><p class="formula">Sₓ(f) = |H(f)|² Sꜰ(f)</p><p>力的功率谱单位为 N²/Hz，位移功率谱为 m²/Hz。这里要乘柔度的平方；仅有功率谱，不能唯一确定一段时程的相位。</p></details></div><div data-panel="time"><div class="transfer-pills">${weights.filter(pt=>pt.amp>0).map(pt=>`<span>${pt.f} Hz：${num(pt.amp)} N → <b>${num(pt.amp*pt.D/k*100)} cm</b><small>滞后 ${num(pt.phase*180/Math.PI,1)}°</small></span>`).join('')||'<p>所有输入幅值为 0，响应也为 0。</p>'}</div><p class="micro-question">下方时程由各频率的响应按各自幅值和相位叠加得到。</p></div><p id="range-warning" class="warning" hidden></p><button data-param="displayRange" data-value="${scale<60?60:12}" class="text-button">${scale<60?'展宽时程纵轴至 ±60 N':'恢复时程纵轴至 ±12 N'}</button>`;
 }
 function applyView(){if(idx!==3&&idx!==5)return;const view=views[idx];document.querySelectorAll('#view-navigation [data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===view)));$('#view-select').value=view;host.querySelectorAll('[data-panel]').forEach(el=>el.hidden=el.dataset.panel!==view);$('.chart-wrap').hidden=!(idx===5&&view==='time');}
 function draw(s){lastState=s;const {idx:i,t,phase,r,params}=s;PhaseViews.update(t,s);if(i!==3&&i!==5)return;host.hidden=false;applyView();
  if(i===3){$('#force-ma').textContent=signed(r.ma)+' N';$('#force-cv').textContent=signed(r.cv)+' N';$('#force-kx').textContent=signed(r.kx)+' N';$('#force-f').textContent=signed(r.F)+' N';$('#force-sum').innerHTML=`惯性项 + 弹性项 = <b>${signed(r.ma+r.kx)} N</b>`;$('#force-check').textContent=`三项之和 = ${signed(r.ma+r.cv+r.kx)} N；与外力之差 ${Math.abs(r.ma+r.cv+r.kx-r.F).toExponential(1)} N`;$('#motion-values').innerHTML=`<span>x<b>${num(r.xSI,3)} m</b></span><span>ẋ<b>${num(r.vSI,3)} m/s</b></span><span>ẍ<b>${num(r.aSI,3)} m/s²</b></span>`;
    host.querySelectorAll('.deep-cursor').forEach(el=>{el.setAttribute('x1',92+t/end*516);el.setAttribute('x2',92+t/end*516);});
  }
  const warning=$('#range-warning');if(warning){warning.hidden=maxTrace<=scale;warning.textContent=`完整记录的${i===3?'位移倍率或方程项的最大绝对值':'kx 峰值'}约 ${num(maxTrace)}${i===3?'（位移为倍数，力项为 N）':' N'}，超过当前 ±${scale} 刻度；曲线在图框处裁切，可点下方展宽。原始数值未截断。`;}
 }
 return {setup,draw};
})();
