/* Source-derived linked views. Fixed time windows, separate physical meanings for each graph. */
const PhaseViews=(()=>{
 const $=s=>document.querySelector(s),Dg=DynamicsDiagnostics,B='#1664b7',O='#b84f19',G='#8293a3',T='#0b746c',V='#7951a8',I='#172d40';
 let context=null,tracked=[],orbits=[],serial=0,settings={orbit:'actual',frequencyMax:3};
 const fixed=(v,n=2)=>Number(v).toFixed(n),clean=(v,n=2)=>Math.abs(v)<1e-9?'0':fixed(v,n);
 const path=(points)=>points.map((p,i)=>(i?'L':'M')+p.map(v=>fixed(v,3)).join(',')).join(' ');
 function chart({id,title,xLabel,yLabel,xMin=0,xMax,yMin,yMax,curves=[],points=[],annotations='',height=280,track=false}){
  const w=640,left=74,right=610,top=38,bottom=height-55,x=v=>left+(v-xMin)/(xMax-xMin)*(right-left),y=v=>bottom-(v-yMin)/(yMax-yMin)*(bottom-top),clip='diag-clip-'+serial++;
  let svg=`<defs><clipPath id="${clip}"><rect x="${left}" y="${top}" width="${right-left}" height="${bottom-top}"/></clipPath></defs>`;
  for(let j=0;j<=4;j++){const v=xMin+(xMax-xMin)*j/4,xx=x(v);svg+=`<line x1="${xx}" x2="${xx}" y1="${top}" y2="${bottom}" stroke="#e2e9f0"/><text x="${xx}" y="${bottom+27}" text-anchor="middle">${clean(v,Math.abs(xMax-xMin)>8?1:2)}</text>`;}
  for(let j=0;j<=2;j++){const v=yMin+(yMax-yMin)*j/2,yy=y(v);svg+=`<line x1="${left}" x2="${right}" y1="${yy}" y2="${yy}" stroke="${j===1?'#c1cfdd':'#e2e9f0'}"/><text x="${left-9}" y="${yy+7}" text-anchor="end">${clean(v,Math.max(Math.abs(yMin),Math.abs(yMax))>=100?0:Math.max(Math.abs(yMin),Math.abs(yMax))>8?1:2)}</text>`;}
  svg+=`<text x="${left}" y="24">${yLabel}</text><text x="${right}" y="${height-5}" text-anchor="end">${xLabel}</text>`;
  svg+=`<g clip-path="url(#${clip})">${curves.map(c=>`<path d="${path(c.values.map(a=>[x(a[0]),y(a[1])]))}" fill="none" stroke="${c.color||B}" stroke-width="${c.width||3}" ${c.dash?'stroke-dasharray="8 6"':''} ${c.opacity?'opacity="'+c.opacity+'"':''}/>`).join('')}${points.map(a=>`<circle cx="${x(a.x)}" cy="${y(a.y)}" r="6" fill="${a.color||B}"/>`).join('')}</g>${annotations?annotations({x,y,top,bottom,left,right}):''}`;
  if(track){svg+=`<line id="${id}-cursor" x1="${left}" x2="${left}" y1="${top}" y2="${bottom}" stroke="${T}" stroke-width="2"/><circle id="${id}-dot" cx="${left}" cy="${y(0)}" r="6" fill="${B}"/>`;tracked.push({id,x,y,clip:[yMin,yMax],value:track});}
  return `<svg id="${id}" class="diagnostic-chart" viewBox="0 0 640 ${height}" role="img" aria-label="${title}">${svg}</svg>`;
 }
 const card=(title,why,body,note='',wide=false)=>`<section class="diagnostic-card ${wide?'diagnostic-wide':''}"><h3>${title}</h3><p class="diagnostic-purpose">${why}</p>${body}${note?`<p class="diagnostic-note">${note}</p>`:''}</section>`;
 function orbit({id,title,why,samples,xval,yval,xlim,ylim,xLabel,yLabel,note,reference=[]}){
  const values=samples.map(s=>[xval(s),yval(s)]),curves=[...reference,{values,color:B}],sv=chart({id,title,xLabel,yLabel,xMin:-xlim,xMax:xlim,yMin:-ylim,yMax:ylim,curves,height:629,annotations:({x,y,left,right,top,bottom})=>`<line x1="${x(0)}" x2="${x(0)}" y1="${top}" y2="${bottom}" stroke="#a6b8ca"/><line x1="${left}" x2="${right}" y1="${y(0)}" y2="${y(0)}" stroke="#a6b8ca"/><circle id="${id}-state" r="7" cx="${x(values[0][0])}" cy="${y(values[0][1])}" fill="${O}" stroke="white" stroke-width="2"/><path id="${id}-direction" fill="none" stroke="${O}" stroke-width="2.5"/>`});
  orbits.push({id,xval,yval,xlim,ylim,values});return card(title,why,sv,note);
 }
 function sampleTimes(duration,count=801){return Array.from({length:count},(_,j)=>j*duration/(count-1));}
 function steadySample(t,p){const q=Dg.harmonicInfo(p),r=Physics.harmonic(t,{r:q.r,z:q.z,m:q.m,k:q.k,rest:false});return {...r,xSI:r.x,vSI:r.v,x:r.x*q.k,k:q.k,fn:q.fn};}
 function resonance(p,sample,end,scale){
  tracked=[];orbits=[];context={idx:3,p,sample,end,scale};const q=Dg.harmonicInfo(p),times=sampleTimes(end,Math.max(801,Math.ceil(end*Math.max(q.fn,p.frequency)*64)+1)),data=times.map(sample),steady=sampleTimes(q.T,721).map(t=>steadySample(t,p)),cp=t=>Dg.components(t,p),isStart=p.response==='start';
  const info=`<div class="diagnostic-summary"><span>频率比 r<b>${fixed(q.r,3)}</b></span><span>动力放大 D<b>${fixed(q.D,3)}</b></span><span>位移振幅 X<b>${fixed(q.X*100)} cm</b></span><span>滞后 φ<b>${fixed(q.phi*180/Math.PI,1)}°</b></span></div><p class="diagnostic-link">静力位移 F₀/k = ${fixed(100/q.k)} cm；稳态振幅 X = D × F₀/k。${isStart?'当前曲线包含启动瞬态；D 和 φ 描述最终稳态。':'所有图对应同一个稳态；播放只移动共同的时间标记。'}</p>`;
  const actual=card('外力与位移时程','比较实际放大：两条线使用同一个纵轴尺度。',chart({id:'force-displacement-time',title:'固定时间窗内外力和位移时程',xLabel:'时间 t / s',yLabel:'F/F₀，kx/F₀',xMax:end,yMin:-scale,yMax:scale,curves:[{values:times.map((t,i)=>[t,data[i].F]),color:O,dash:true},{values:times.map((t,i)=>[t,data[i].x]),color:B}],track:t=>sample(t).x}),`橙色虚线：F/F₀；蓝线：kx/F₀。${isStart?'此处为总响应，不给启动曲线强行标一个恒定相位。':'蓝线的振幅就是 D。'}超界时请用上方“固定量程”选择大量程。`,true);
  const phaseAnnotation=({x,top,bottom})=>q.responsePeak>end?`<text x="342" y="${top+26}" text-anchor="middle">本窗口不含完整峰对；Δt = ${fixed(q.delay,3)} s</text>`:`<line x1="${x(q.forcePeak)}" x2="${x(q.forcePeak)}" y1="${top}" y2="${bottom}" stroke="${O}" stroke-dasharray="4 5"/><line x1="${x(q.responsePeak)}" x2="${x(q.responsePeak)}" y1="${top}" y2="${bottom}" stroke="${B}" stroke-dasharray="4 5"/><path d="M${x(q.forcePeak)} ${top+18}H${x(q.responsePeak)}" stroke="${V}" stroke-width="3"/><text x="${Math.min(460,Math.max(160,(x(q.forcePeak)+x(q.responsePeak))/2))}" y="${top+48}" text-anchor="middle" fill="${V}">Δt = ${fixed(q.delay,3)} s</text>`;
  const alignment=card('同频波形的相位差','只比较先后：各自除以幅值，再标出相应的两个波峰。',chart({id:'phase-time',title:'归一化外力与位移的相位时差',xLabel:'时间 t / s',yLabel:'F/F₀，x/X',xMax:end,yMin:-1.5,yMax:1.5,curves:[{values:times.map(t=>[t,Math.sin(q.omega*t)]),color:O,dash:true},{values:times.map(t=>[t,Math.sin(q.omega*t-q.phi)]),color:B}],annotations:phaseAnnotation,track:t=>Math.sin(q.omega*t-q.phi)}),`φ = 360° × Δt/T = ${fixed(q.phi*180/Math.PI,1)}°，T = ${fixed(q.T,3)} s。此图隐藏了振幅倍率，不能用峰高判断 D。${isStart?'这是最终稳态的相位参照。':''}`,true);
  const normalized=settings.orbit==='shape',shapeLimit=isStart?Math.max(1.25,Math.ceil(Math.max(...data.map(s=>Math.abs(s.x/q.D)))*1.1*4)/4):1.25;
  const forceOrbit=orbit({id:'load-orbit',title:'外力—位移关系图',why:'由原代码的 F—kx 关系图展开：每个点配对同一时刻的外力和位移。',samples:isStart?data:steady,xval:s=>normalized?s.x/q.D:s.x,yval:s=>s.F,xlim:normalized?shapeLimit:scale,ylim:1.25,xLabel:normalized?'位移 x/X':'位移 kx/F₀',yLabel:'外力 F/F₀',note:`橙点与时程游标同步。${normalized?'横轴除以稳态振幅。稳态下两轴等比例，90°对应圆形轨迹。':'当前横轴保留实际倍率，宽度随 D 变化。'}${isStart?'启动轨迹未必闭合；灰虚线是最终稳态环。'+(normalized?'启动横轴按总响应展宽，不能直接比较圆度。':''):'轨迹的展开与倾斜反映外力和位移的相位关系。'}`,reference:isStart?[{values:steady.map(s=>[normalized?s.x/q.D:s.x,s.F]),color:G,dash:true}]:[]});
  const stateX=scale,stateV=scale;
  const stateOrbit=orbit({id:'state-orbit',title:'位移—速度相图',why:'横轴是位移，纵轴是速度；用固定尺度比较同一系统的不同工况。',samples:isStart?data:steady,xval:s=>s.x,yval:s=>s.v/q.wn,xlim:stateX,ylim:stateV,xLabel:'位移 x/x静 = kx/F₀',yLabel:'速度 v/(ωₙx静)',note:'两轴以静力位移和固有角频率为尺度；只随手动量程改变。超出图框时需选择大量程。',reference:isStart?[{values:steady.map(s=>[s.x,s.v/q.wn]),color:G,dash:true}]:[]});
  const shapeControls=`<div class="diagnostic-options"><span>外力—位移图横轴</span><button data-diag-setting="orbit" data-value="shape" aria-pressed="${normalized}">只看相位形状</button><button data-diag-setting="orbit" data-value="actual" aria-pressed="${!normalized}">保留振幅倍率</button></div>`;
  const fullDomain=50,domain=settings.frequencyMax===3?3:fullDomain,ratios=InstrumentScale.ratios(p.damping,domain),dt=ratios.map(r=>[r,Dg.transfer(r,p.damping).D]),pt=ratios.map(r=>[r,Dg.transfer(r,p.damping).phi*180/Math.PI]),marker=q.r<=domain;
  const frequency=`${info}<div class="diagnostic-options"><span>固定频率比横轴</span><button data-diag-setting="frequencyMax" data-value="3" aria-pressed="${domain===3}">0—3，细看共振</button><button data-diag-setting="frequencyMax" data-value="12" aria-pressed="${settings.frequencyMax===12}">0—${fullDomain}，全范围</button></div>${!marker?'<p class="warning">当前频率比超出横轴，请切换到“全范围”查看当前位置。</p>':''}<div class="diagnostic-grid">${card('动力放大曲线 D(r)','一个频率对应一个稳态振幅倍率；圆点是当前外力频率。',chart({id:'daf-curve',title:'动力放大系数随频率比变化',xLabel:'r = 外力频率 / 自身频率',yLabel:'D = X / (F₀/k)',xMax:domain,yMin:0,yMax:scale,curves:[{values:dt,color:B}],points:marker?[{x:q.r,y:q.D,color:O}]:[]}),`D = ${fixed(q.D,3)}，X = ${fixed(q.X*100)} cm。曲线纵轴固定为 0—${scale}。有阻尼时位移峰略低于 r = 1。`,true)}${card('相频曲线 φ(r)','与上图用同一条频率比横轴；这里看位移相对外力滞后多少。',chart({id:'phase-response',title:'位移相位滞后随频率比变化',xLabel:'r = 外力频率 / 自身频率',yLabel:'相位滞后 φ / °',xMax:domain,yMin:0,yMax:180,curves:[{values:pt,color:V}],points:marker?[{x:q.r,y:q.phi*180/Math.PI,color:O}]:[]}),`当前 φ = ${fixed(q.phi*180/Math.PI,1)}°。本图与 D 曲线都是稳态特性，不描述启动过程中单一恒定相位。`,true)}</div>`;
  const componentCurves=[{values:times.map(t=>[t,cp(t).total*q.k]),color:B},{values:times.map(t=>[t,cp(t).steady*q.k]),color:O,dash:true},{values:times.map(t=>[t,cp(t).transient*q.k]),color:V}];
  const transient=card('从静止启动：总响应 = 稳态 + 瞬态','三条记录共用固定的时间轴，先区分最终持续的部分与逐渐消失的部分。',chart({id:'startup-components',title:'受迫启动响应分解',xLabel:'时间 t / s',yLabel:'kx/F₀',xMax:end,yMin:-scale,yMax:scale,curves:componentCurves,track:t=>cp(t).total*q.k}),'蓝线：总响应；橙虚线：最终稳态；紫线：自由瞬态。分解满足初始位移、速度都为零。',true);
  const envelope=card('自由瞬态的衰减包络','包络约束的是瞬态分量；不是把总响应直接包成 ±Ae⁻ᵃᵗ。',chart({id:'transient-envelope',title:'启动自由瞬态与指数衰减包络',xLabel:'时间 t / s',yLabel:'kxₕ/F₀',xMax:end,yMin:-scale,yMax:scale,curves:[{values:times.map(t=>[t,cp(t).transient*q.k]),color:V},{values:times.map(t=>[t,cp(t).envelope*q.k]),color:T,dash:true},{values:times.map(t=>[t,-cp(t).envelope*q.k]),color:T,dash:true}],track:t=>cp(t).transient*q.k}),'绿色虚线：±R e⁻ζωₙᵗ。R 由满足零初始条件所需的自由振动系数计算。',true);
  const boundLimit=scale;
  const totalBounds=card('总响应的边界：围绕稳态上下浮动','将衰减包络加到稳态曲线上，得到总响应所在的上下边界。',chart({id:'total-envelope',title:'总响应与以稳态为中心的上下边界',xLabel:'时间 t / s',yLabel:'kx/F₀',xMax:end,yMin:-boundLimit,yMax:boundLimit,curves:[{values:times.map(t=>[t,cp(t).lower*q.k]),color:T,dash:true},{values:times.map(t=>[t,cp(t).upper*q.k]),color:T,dash:true},{values:times.map(t=>[t,cp(t).steady*q.k]),color:O,dash:true},{values:times.map(t=>[t,cp(t).total*q.k]),color:B}],track:t=>cp(t).total*q.k}),`绿色边界：xₛ(t) ± R e⁻ζωₙᵗ；蓝线是总响应。该图纵轴固定为 ±${boundLimit}；超出图框时请手动展宽；时间范围仍固定为 0—${end} s。`,true);
  return {phase:`${info}<div class="diagnostic-grid">${actual}${alignment}</div>${shapeControls}<div class="diagnostic-grid">${forceOrbit}${stateOrbit}</div>`,frequency,envelope:isStart?`<p class="diagnostic-link">固定显示 0—${end} s；改变频率不会改变这个时间范围。</p><div class="diagnostic-grid">${transient}${envelope}${totalBounds}</div>`:`<p class="diagnostic-link">当前选择“持续推动后”，没有启动瞬态。可直接切换观察阶段，查看从静止启动的分解与包络。</p><button class="primary" data-param="response" data-value="start">切换到从静止启动</button>`};
 }
 function free(i,p,sample,end,scale=1.6){tracked=[];orbits=[];context={idx:i,p,sample,end};const k=Physics.tau**2,m=i===1?p.mass:1,z=i===2?p.damping:0,x0=(p.amplitude??1)*.01,times=sampleTimes(end),data=times.map(sample),valid=z<1,env=t=>Dg.freeEnvelope(t,{k,m,z,x0})*100;
  const freeCurves=[...(i===1||i===2?[{values:times.map((t,j)=>[t,data[j].ref]),color:G,dash:true}]:[]),{values:times.map((t,j)=>[t,data[j].x]),color:B},...(valid?[{values:times.map(t=>[t,env(t)]),color:T,dash:true},{values:times.map(t=>[t,-env(t)]),color:T,dash:true}]:[])];
  const report=card(valid?(z<0?'负阻尼：振动与包络增长':z>0?'自由振动与指数包络':'自由振动与恒定包络'):'临界与过阻尼回位',valid?'将位移时程与它的振幅边界放在一起，固定时间与位移刻度。':'当前不再往返振荡，仍显示完整回位曲线；欠阻尼包络不适用于这里。',chart({id:'free-envelope',title:'自由响应时程与适用的包络',xLabel:'时间 t / s',yLabel:'位移 / cm',xMax:end,yMin:-scale,yMax:scale,curves:freeCurves,track:t=>sample(t).x}),`蓝线：当前位移。${i===1?'灰虚线：原来的 1 kg。':i===2?'灰虚线：无阻尼基准。':''}${valid?'绿色虚线：数学包络。'+(z<0?'ζ 为负时，指数包络随时间增长；负阻尼表示外部能量输入。':z>0?'静止释放时的包络系数为 |x₀|/√(1−ζ²)。接近临界阻尼时包络可能超过图框。':'无阻尼时包络不衰减。'):'当前不画欠阻尼包络。'}`,true);
  return `<div class="diagnostic-grid">${report}${orbit({id:'free-state',title:'位移—速度相图',why:'同一条运动记录换一种坐标看：每个点都包含位移与速度。',samples:data,xval:s=>s.x,yval:s=>s.v,xlim:scale,ylim:z<0?scale*Physics.tau:Math.max(10,...data.map(s=>Math.abs(s.v)*1.12)),xLabel:'位移 x / cm',yLabel:'速度 v / (cm/s)',note:'无阻尼时轨迹闭合；正阻尼时向内收缩；负阻尼时向外扩展。橙色点和方向箭头跟随当前时间。'})}</div>`;
 }
 function pulse(p,sample,end){tracked=[];orbits=[];context={idx:4,p,sample,end};const times=sampleTimes(end),data=times.map(sample),q=sample(p.duration),z=.04,w=Physics.tau,wd=w*Math.sqrt(1-z*z),R=Math.hypot(q.x,(q.v+z*w*q.x)/wd),tail=times.filter(t=>t>=p.duration),env=t=>R*Math.exp(-z*w*(t-p.duration));
  return `<div class="diagnostic-grid">${card('撤力后的自由振动包络','撤力瞬间的位移与速度共同决定剩余振幅。',chart({id:'pulse-envelope',title:'短时荷载撤去后的振动及包络',xLabel:'时间 t / s',yLabel:'kx/F₀，F/F₀',xMax:end,yMin:-2.2,yMax:2.2,curves:[{values:[[0,1],[p.duration,1],[p.duration,0],[end,0]],color:O,dash:true},{values:times.map((t,j)=>[t,data[j].x]),color:B},{values:tail.map(t=>[t,env(t)]),color:T,dash:true},{values:tail.map(t=>[t,-env(t)]),color:T,dash:true}],track:t=>sample(t).x,annotations:({x,top,bottom})=>`<rect x="${x(0)}" y="${top}" width="${x(p.duration)-x(0)}" height="${bottom-top}" fill="${O}" opacity=".06"/><line x1="${x(p.duration)}" x2="${x(p.duration)}" y1="${top}" y2="${bottom}" stroke="${O}" stroke-dasharray="5 5"/><text x="${Math.max(150,x(p.duration))}" y="${top+26}" text-anchor="middle">撤力 ${fixed(p.duration,1)} s</text>`}),`橙虚线：荷载 F/F₀；蓝线：位移 kx/F₀；绿色虚线：撤力后的包络，从 ${fixed(p.duration,1)} s 开始。`,true)}${orbit({id:'pulse-state',title:'加载与撤力的状态轨迹',why:'同一个物体在施力期间和撤力以后，沿不同的轨迹运动。',samples:data,xval:s=>s.x,yval:s=>s.v,xlim:2.2,ylim:15,xLabel:'位移 kx/F₀',yLabel:'速度 kv/F₀ / s⁻¹',note:'横纵轴都是由同一个静力位移尺度归一化的物理量；橙点对应当前时刻。'})}</div>`;
 }
 function update(t,s){for(const c of tracked){const line=$('#'+c.id+'-cursor'),dot=$('#'+c.id+'-dot');if(!line||!dot)continue;const v=c.value(t);line.setAttribute('x1',c.x(t));line.setAttribute('x2',c.x(t));dot.setAttribute('cx',c.x(t));dot.setAttribute('cy',c.y(v));dot.style.visibility=v<c.clip[0]||v>c.clip[1]?'hidden':'visible';}
  if(!context)return;const cur=context.sample(t),next=context.sample(Math.min(context.end,t+.015));for(const o of orbits){const dot=$('#'+o.id+'-state'),direction=$('#'+o.id+'-direction');if(!dot)continue;const xx=v=>74+(v+o.xlim)/(2*o.xlim)*536,yy=v=>574-(v+o.ylim)/(2*o.ylim)*536,x=xx(o.xval(cur)),y=yy(o.yval(cur)),dx=xx(o.xval(next))-x,dy=yy(o.yval(next))-y,l=Math.hypot(dx,dy),inside=Math.abs(o.xval(cur))<=o.xlim&&Math.abs(o.yval(cur))<=o.ylim;dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.style.visibility=inside?'visible':'hidden';if(l>1e-8&&inside){const ux=dx/l,uy=dy/l,ex=x+ux*19,ey=y+uy*19;direction.setAttribute('d',`M${x},${y}L${ex},${ey}M${ex-ux*7-uy*4},${ey-uy*7+ux*4}L${ex},${ey}L${ex-ux*7+uy*4},${ey-uy*7-ux*4}`);}else direction.setAttribute('d','');}}
 function set(key,value){if(key==='orbit')settings.orbit=value;else if(key==='frequencyMax')settings.frequencyMax=Number(value);}
 function reset(){tracked=[];orbits=[];context=null;}
 return {resonance,free,pulse,update,set,reset};
})();
