/* A selected single-frequency steady experiment; playback never changes f. */
const SpectrumLab=(()=>{
 const B='#1664b7',O='#b84f19',T='#0b746c',V='#8655a3';let p,observer,last=0;
 const $=s=>document.querySelector(s),f=(x,n=2)=>Number(x).toFixed(n);
 function info(a=p,r=a.frequency/a.natural){const z=a.damping,D=1/Math.hypot(1-r*r,2*z*r),phi=Math.atan2(2*z*r,1-r*r),rp=Math.sqrt(1-2*z*z),peak=1/(2*z*Math.sqrt(1-z*z)),lo=Math.sqrt(1-2*z*z-2*z*Math.sqrt(1-z*z)),hi=Math.sqrt(1-2*z*z+2*z*Math.sqrt(1-z*z)),k=(Physics.tau*a.natural)**2;return {r,D,phi,rp,peak,lo,hi,k,Ax:a.force/k*D};}
 function setup(params){p=params;const r=p.frequency/p.natural,cases=[[.5,'低频'],[1,'共振'],[2,'高频']],selected=cases.some(([a])=>Math.abs(a-r)<1e-8);$('#frequency-strip').innerHTML='';$('#experiment-tools').innerHTML=`<label class="case-select-label">频率<select id="single-case">${cases.map(([a,label])=>`<option value="${a}" ${Math.abs(a-r)<1e-8?'selected':''}>${label} · ${a} fₙ</option>`).join('')}<option value="manual" ${!selected?'selected':''}>手动设置</option></select></label>`+InstrumentScale.selector(p);$('#compact-views').hidden=false;$('#compact-views').innerHTML='<section class="compact-panel spectrum-main"><h3>动力放大 D · 当前频率对应的倍率</h3><canvas id="sweep-gain" role="img" aria-label="固定坐标动力放大曲线"></canvas><small id="sweep-stats"></small></section><section class="compact-panel"><h3>幅值谱 · 荷载 → 刚度×位移</h3><canvas id="sweep-lines" role="img" aria-label="固定坐标同频输入响应谱"></canvas><small id="sweep-pair"></small></section><section class="compact-panel"><h3>同频响应 · 直接比较放大</h3><canvas id="sweep-wave" role="img" aria-label="固定幅值坐标的荷载和位移时程"></canvas><small id="wave-scale-note"></small></section>';if(!observer){observer=new ResizeObserver(()=>draw(last));observer.observe($('#compact-views'));}draw(0);}
 function surface(id){const e=$('#'+id),r=e.getBoundingClientRect(),d=Math.min(3,devicePixelRatio||1);if(!r.width||!r.height)return null;e.width=Math.round(r.width*d);e.height=Math.round(r.height*d);e.dataset.scale=String(InstrumentScale.limit(p));const c=e.getContext('2d');c.scale(d,d);c.font='12px "Microsoft YaHei",sans-serif';c.lineJoin='round';return {c,w:r.width,h:r.height};}
 function line(c,pts,color,dash=[],width=1.7){c.beginPath();pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.strokeStyle=color;c.setLineDash(dash);c.lineWidth=width;c.stroke();c.setLineDash([]);}
 function dot(c,x,y,color){c.fillStyle=color;c.beginPath();c.arc(x,y,3.5,0,7);c.fill();}
 function draw(t){last=t;if(!p||!$('#sweep-gain'))return;const q=info(),L=InstrumentScale.limit(p),overflow=p.force*q.D>L;
 $('#sweep-stats').textContent=`ζ=${f(p.damping,3)} · 峰 ${f(q.peak,1)} · 带宽 ${f((q.hi-q.lo)*p.natural,4)} Hz`;
 $('#sweep-pair').textContent=`D=${f(q.D,2)} · X=${f(q.Ax*100)} cm · 滞后 ${f(q.phi*180/Math.PI,1)}°`;
 $('#wave-scale-note').textContent=overflow?`↑ 响应 ${f(p.force*q.D,1)} 超出 ±${L}；手动选大量程`:`橙 F / 蓝 kx（N）· 固定 ±${L}，0—4 s`;
 $('#wave-scale-note').style.color=overflow?O:'';
 let s=surface('sweep-gain');if(s){const {c,w,h}=s,l=32,right=w-10,b=h-22,top=22,x=r=>l+r/3*(right-l),y=d=>b-d/L*(b-top);c.fillStyle='#536575';c.fillText('D',3,13);c.fillText(String(L),2,top+4);c.fillText('0',17,b+3);line(c,[[l,b],[right,b]],'#c4d2df');c.save();c.beginPath();c.rect(l,top,right-l,b-top);c.clip();c.fillStyle='#e4eceb';c.fillRect(x(q.lo),top,x(q.hi)-x(q.lo),b-top);for(const [z,color] of [[.02,V],[.07,O],[.2,T]])line(c,InstrumentScale.ratios(z,3).map(r=>[x(r),y(info({...p,damping:z},r).D)]),color,[3,3],1);
 const points=InstrumentScale.ratios(p.damping,3).concat(q.lo,q.hi).sort((a,b)=>a-b);line(c,points.map(r=>[x(r),y(info(p,r).D)]),B,[],2.4);line(c,[[x(q.lo),y(q.peak/Math.SQRT2)],[x(q.hi),y(q.peak/Math.SQRT2)]],T,[],3);c.restore();dot(c,x(q.r),y(Math.min(q.D,L)),B);if(q.peak>L){c.fillStyle=B;c.fillText('↑ 峰 '+f(q.peak,1),x(q.rp)+7,top+12);}for(let j=0;j<=3;j++){c.fillStyle='#536575';c.textAlign='center';c.fillText(String(j),x(j),b+15);}c.textAlign='right';c.fillText('r = f/fₙ',right,12);c.textAlign='left';[[.02,V],[.07,O],[.2,T]].forEach(([z,color],j)=>{c.fillStyle=color;c.fillText('ζ '+f(z),38+j*62,12);});}
 s=surface('sweep-lines');if(s){const {c,w,h}=s,half=w/2,bottom=h-16,top=22,room=Math.max(10,bottom-top);for(const [j,color,label,amplitude] of [[0,O,'F₀ = '+f(p.force)+' N',p.force],[1,B,'kX = '+f(p.force*q.D)+' N',p.force*q.D]]){const l=j*half+25,right=(j+1)*half-8,x=l+q.r/3*(right-l),height=room*Math.min(amplitude,L)/L;c.fillStyle=color;c.textAlign='left';c.fillText(label,l-6,12);line(c,[[l,bottom],[right,bottom]],'#bacad7');line(c,[[x,bottom],[x,bottom-height]],color,[],4);dot(c,x,bottom-height,color);if(amplitude>L)c.fillText('↑',x+5,top+12);c.fillStyle='#536575';c.fillText('0',l-7,bottom+13);c.fillText(String(L),j*half+1,top+5);c.textAlign='right';c.fillText('3 fₙ',right,bottom+13);c.textAlign='left';}c.fillStyle='#536575';c.textAlign='center';c.fillText('→',half,Math.max(30,h/2));}
 s=surface('sweep-wave');if(s){const {c,w,h}=s,l=32,right=w-9,top=9,bottom=h-18,cy=(top+bottom)/2,xx=time=>l+time/4*(right-l),yy=v=>cy-v/L*(bottom-top)/2;line(c,[[l,cy],[right,cy]],'#c5d3df');c.save();c.beginPath();c.rect(l,top,right-l,bottom-top);c.clip();for(const [color,gain,phase] of [[O,p.force,0],[B,p.force*q.D,q.phi]])line(c,Array.from({length:801},(_,j)=>[xx(j/200),yy(gain*Math.sin(Physics.tau*p.frequency*j/200-phase))]),color);c.restore();c.fillStyle='#536575';c.fillText(String(L),0,top+4);c.fillText('−'+L,0,bottom);c.fillText('0',l,h-2);c.textAlign='right';c.fillText('4 s',right,h-2);line(c,[[xx(t%4),top],[xx(t%4),bottom]],T,[3,3]);dot(c,xx(t%4),yy(InstrumentScale.clamp(p.force*q.D*Math.sin(Physics.tau*p.frequency*(t%4)-q.phi),L)),B);}
 }
 return {setup,draw,info};
})();
