/* Canonical 3D solids, projected in an orthographic engineering view. */
const StructuralView=(()=>{
 let selected='cart',last=0,limit=1.6,observer;
 const $=s=>document.querySelector(s);
 function setup(i,p,axisLimit){limit=axisLimit;const el=$('#model-canvas');if(i>2){el.hidden=true;$('#apparatus').removeAttribute('hidden');return;}$('#experiment-tools').insertAdjacentHTML('beforeend','<label class="case-select-label model-select">外观<select id="structure-model"><option value="cart">小车与弹簧</option><option value="bridge">简支梁桥 · 三维</option><option value="building">六层建筑 · 三维</option></select></label>');if(!observer){observer=new ResizeObserver(()=>draw(last));observer.observe(el);}$('#structure-model').value=selected;$('#structure-model').onchange=e=>{selected=e.target.value;draw(last);};draw(last);}
 function draw(q){last=q;const el=$('#model-canvas');if(!$('#structure-model'))return;el.hidden=selected==='cart';const hint=document.querySelector('.drag-instruction,.damping-state span');if(hint)hint.textContent=selected==='cart'?'拖开小车，松手释放':'按开始观看；切回小车可拖拽';$('#apparatus').toggleAttribute('hidden',selected!=='cart');if(el.hidden)return;const model=STRUCTURAL_ASSETS.models.find(m=>m.model_id.includes(selected)),rect=el.getBoundingClientRect();if(!rect.width||!rect.height)return;const d=Math.min(3,devicePixelRatio||1),w=rect.width,h=rect.height;el.width=w*d;el.height=h*d;const c=el.getContext('2d');c.scale(d,d);c.lineJoin='round';const bridge=selected==='bridge',magnitude=(bridge?2:3)/limit,axis=bridge?[0,0,1]:[1,0,0],raw=v=>[v[0]*.9-v[1]*.6,-v[2]+v[0]*.12+v[1]*.28],all=model.meshes.flatMap(m=>m.vertices.map(raw)),xmin=Math.min(...all.map(a=>a[0])),xmax=Math.max(...all.map(a=>a[0])),ymin=Math.min(...all.map(a=>a[1]))-3,ymax=Math.max(...all.map(a=>a[1]))+3,scale=Math.min((w-28)/(xmax-xmin),(h-23)/(ymax-ymin)),project=v=>{const r=raw(v);return [w/2+(r[0]-(xmin+xmax)/2)*scale,(h-16)/2+(r[1]-(ymin+ymax)/2)*scale];},faces=[];
 for(const m of model.meshes){const vs=m.vertices.map((v,j)=>v.map((x,k)=>x+axis[k]*m.phi[j]*q*magnitude));for(const face of STRUCTURAL_ASSETS.geometry_contract.face_vertex_indices){const vertices=face.map(j=>vs[j]);faces.push({pts:vertices.map(project),depth:vertices.reduce((a,v)=>a+v[0]*.3+v[1]-.15*v[2],0)/4,color:STRUCTURAL_ASSETS.materials[m.material].color});}}
 for(const m of model.meshes.filter((m,j)=>m.material==='floor'||(m.material==='deck'&&j%10===0))){c.beginPath();[4,5,6,7,4].forEach((n,j)=>{const [x,y]=project(m.vertices[n]);j?c.lineTo(x,y):c.moveTo(x,y);});c.strokeStyle='#879bad';c.lineWidth=1;c.setLineDash([3,3]);c.stroke();c.setLineDash([]);}faces.sort((a,b)=>b.depth-a.depth);for(const face of faces){c.beginPath();face.pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fillStyle=face.color;c.fill();c.strokeStyle='#42647a66';c.lineWidth=.65;c.stroke();}c.fillStyle='#536575';c.font='12px "Microsoft YaHei",sans-serif';c.fillText('同一 q(t) 驱动 · 变形放大 ×'+Math.round(magnitude*100)+' · 虚线原位',6,h-4);}
 return {setup,draw};
})();
